version: "3.7"
services:
  app:
    build:
      args:
        user: techshop
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: techshop
    container_name: techshop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - techshop

  db:
    image: mysql:5.7
    container_name: techshop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - techshop

  nginx:
    image: nginx:alpine
    container_name: techshop-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - techshop
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: techshop-phpmyadmin
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./docker-compose/phpmyadmin:/var/www/html
    networks:
      - techshop

networks:
  techshop:
    driver: bridge
